version: "3.7"
services:
    app:
        build:
            args:
                user: rickneves
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: challengeom30
        container_name: challengeom30-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - challengeom30

    postgres:
        image: postgres
        container_name: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: challengeom30
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - challengeom30

    postgresadmin:
        image: dpage/pgadmin4
        container_name: postgres-admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ricknevesbc@hotmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        networks:
            - challengeom30

    redis:
        image: redis:latest
        sysctls:
            - net.core.somaxconn=511
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - challengeom30

    nginx:
        image: nginx:1.17-alpine
        container_name: challengeom30-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - challengeom30
networks:
    challengeom30:
        driver: bridge

volumes:
    postgres-data:
    redis-data:
