version: "3.7"
services:
    app:
        build:
            args:
                user: rickneves
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: challengeom30
        container_name: challengeom30-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - challengeom30

    nginx:
        image: nginx:1.17-alpine
        container_name: challengeom30-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - challengeom30
networks:
    challengeom30:
        driver: bridge
